config/routes.rb
Rails.application.routes.draw do
	resources :chirps
	resources :happy_trees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord
end

app/models/happy_tree.rb
class HappyTree < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]

  # GET /chirps
  # GET /chirps.json
  def index
    @chirps = Chirp.all
  end

  # GET /chirps/1
  # GET /chirps/1.json
  def show
  end

  # GET /chirps/new
  def new
    @chirp = Chirp.new
  end

  # GET /chirps/1/edit
  def edit
  end

  # POST /chirps
  # POST /chirps.json
  def create
    @chirp = Chirp.new(chirp_params)

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to @chirp, notice: 'Chirp was successfully created.' }
        format.json { render :show, status: :created, location: @chirp }
      else
        format.html { render :new }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chirps/1
  # PATCH/PUT /chirps/1.json
  def update
    respond_to do |format|
      if @chirp.update(chirp_params)
        format.html { redirect_to @chirp, notice: 'Chirp was successfully updated.' }
        format.json { render :show, status: :ok, location: @chirp }
      else
        format.html { render :edit }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chirps/1
  # DELETE /chirps/1.json
  def destroy
    @chirp.destroy
    respond_to do |format|
      format.html { redirect_to chirps_url, notice: 'Chirp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chirp_params
      params.require(:chirp).permit(:title, :content)
    end
end

app/controllers/happy_trees_controller.rb
class HappyTreesController < ApplicationController
  before_action :set_happy_tree, only: [:show, :edit, :update, :destroy]

  # GET /happy_trees
  # GET /happy_trees.json
  def index
    @happy_trees = HappyTree.all
  end

  # GET /happy_trees/1
  # GET /happy_trees/1.json
  def show
  end

  # GET /happy_trees/new
  def new
    @happy_tree = HappyTree.new
  end

  # GET /happy_trees/1/edit
  def edit
  end

  # POST /happy_trees
  # POST /happy_trees.json
  def create
    @happy_tree = HappyTree.new(happy_tree_params)

    respond_to do |format|
      if @happy_tree.save
        format.html { redirect_to @happy_tree, notice: 'Happy tree was successfully created.' }
        format.json { render :show, status: :created, location: @happy_tree }
      else
        format.html { render :new }
        format.json { render json: @happy_tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happy_trees/1
  # PATCH/PUT /happy_trees/1.json
  def update
    respond_to do |format|
      if @happy_tree.update(happy_tree_params)
        format.html { redirect_to @happy_tree, notice: 'Happy tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @happy_tree }
      else
        format.html { render :edit }
        format.json { render json: @happy_tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happy_trees/1
  # DELETE /happy_trees/1.json
  def destroy
    @happy_tree.destroy
    respond_to do |format|
      format.html { redirect_to happy_trees_url, notice: 'Happy tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_happy_tree
      @happy_tree = HappyTree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def happy_tree_params
      params.require(:happy_tree).permit(:color, :brush, :background, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/happy_trees_helper.rb
module HappyTreesHelper
end

app/views/chirps/_form.html.erb
<%= form_for(chirp) do |f| %>
  <% if chirp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chirp.errors.count, "error") %> prohibited this chirp from being saved:</h2>

      <ul>
      <% chirp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chirps/edit.html.erb
<h1>Editing Chirp</h1>

<%= render 'form', chirp: @chirp %>

<%= link_to 'Show', @chirp %> |
<%= link_to 'Back', chirps_path %>

app/views/chirps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chirps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chirps.each do |chirp| %>
      <tr>
        <td><%= chirp.title %></td>
        <td><%= chirp.content %></td>
        <td><%= link_to 'Show', chirp %></td>
        <td><%= link_to 'Edit', edit_chirp_path(chirp) %></td>
        <td><%= link_to 'Destroy', chirp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chirp', new_chirp_path %>

app/views/chirps/new.html.erb
<h1>New Chirp</h1>

<%= render 'form', chirp: @chirp %>

<%= link_to 'Back', chirps_path %>

app/views/chirps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chirp.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @chirp.content %>
</p>

<%= link_to 'Edit', edit_chirp_path(@chirp) %> |
<%= link_to 'Back', chirps_path %>

app/views/happy_trees/_form.html.erb
<%= form_for(happy_tree) do |f| %>
  <% if happy_tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(happy_tree.errors.count, "error") %> prohibited this happy_tree from being saved:</h2>

      <ul>
      <% happy_tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :brush %>
    <%= f.text_field :brush %>
  </div>

  <div class="field">
    <%= f.label :background %>
    <%= f.check_box :background %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/happy_trees/edit.html.erb
<h1>Editing Happy Tree</h1>

<%= render 'form', happy_tree: @happy_tree %>

<%= link_to 'Show', @happy_tree %> |
<%= link_to 'Back', happy_trees_path %>

app/views/happy_trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Happy Trees</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Brush</th>
      <th>Background</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @happy_trees.each do |happy_tree| %>
      <tr>
        <td><%= happy_tree.color %></td>
        <td><%= happy_tree.brush %></td>
        <td><%= happy_tree.background %></td>
        <td><%= happy_tree.desc %></td>
        <td><%= link_to 'Show', happy_tree %></td>
        <td><%= link_to 'Edit', edit_happy_tree_path(happy_tree) %></td>
        <td><%= link_to 'Destroy', happy_tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Happy Tree', new_happy_tree_path %>

app/views/happy_trees/new.html.erb
<h1>New Happy Tree</h1>

<%= render 'form', happy_tree: @happy_tree %>

<%= link_to 'Back', happy_trees_path %>

app/views/happy_trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @happy_tree.color %>
</p>

<p>
  <strong>Brush:</strong>
  <%= @happy_tree.brush %>
</p>

<p>
  <strong>Background:</strong>
  <%= @happy_tree.background %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @happy_tree.desc %>
</p>

<%= link_to 'Edit', edit_happy_tree_path(@happy_tree) %> |
<%= link_to 'Back', happy_trees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PositiveThings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>